#!/bin/bash
(cd design && vlog -64 -sv -f rtl.cfg)
(cd verif && vlog -64 -sv -f tb.cfg -work work)
(cd verif && vopt -64 alu_32_tb -o tb_top_opt +acc -work work)
(cd sim && vsim -64 -c tb_top_opt -do sim.do)
